### ISSUE TITLE
`env.sh` in `scripts` is perhaps too global

### ISSUE THREAD

**Issue by BenLand100** [DUNE-DAQ/timing#14]
This `scripts` directory is on the global `$PATH` and so `source env.sh` whenever the timing package is setup will execute this script, even taking precedence overf a file `env.sh` in the current working directory:
```
(dbt-pyvenv) [root@60b362592835 WIBSoftwareTrunk]# source env.sh 
uhal is installed
click is installed
Error: package 'click_didyoumean' is not installed
Aborting.
```

What was happening was quite tricky to figure out, since its not marked executable, and thus won't be shown by `which env.sh`. I only found that this script was the one being sourced by:
```
(dbt-pyvenv) [root@60b362592835 WIBSoftwareTrunk]# env.sh
bash: /scratch/ds_workspace_2.6.0/build/timing/scripts/env.sh: Permission denied
```

It should (at least) be renamed to something less general, if it's going to be on `$PATH`.

**Comment by strilov** [comment]
Hi Ben. Thanks for this, and sorry for the late response.

I've marked the script as executable, and renamed it timing_env.sh. I've also moved to test/scripts, which is still on $PATH, but hopefully it won't cause problems now.
