### ISSUE TITLE
UnknownBoardUID crash in PDTS setup

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/timing#3]
The library has to know about the PDSP TLU ID. 

And better catch control would be needed, to avoid crashing with a stack trace that hides the most valuable information:
```
#6  0x00007ffff4d76024 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7fffef040080 <typeinfo for pdt::UnknownBoardUID>, dest=0x7fffeed75534 <pdt::UnknownBoardUID::~UnknownBoardUID()>)
```

**Comment by strilov** [comment]
NP04 TLU UID added to sw db
