### ISSUE TITLE
Provide documentation for users

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/timing#7]
Given the importance of the timing package for the DAQ system, it would be good to write user documentation describing what the package has to offer. Once complete, the Software Coordination Group can add the documentation to the official website (https://dune-daq-sw.readthedocs.io/en/latest). Topics covered could be how the DAQ modules in the package relate to each other, what the configuration parameters do, how to use the Python bindings to the package's functions (when available), etc. 

Technical details on how to add official documentation for a given package are provided at https://dune-daq-sw.readthedocs.io/en/latest/editing_package_documentation/

**Comment by strilov** [comment]
HI John,

I've put together some `timing` documentation here: https://github.com/DUNE-DAQ/timing/pull/13.

Please let me know your thoughts.
